/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TodoApp {
    }
    interface TodoFooter {
        "count": number;
        "filter": Filter;
        "todos": Todo[];
    }
    interface TodoItem {
        "_id": Todo["id"];
        "_title": Todo["title"];
        "completed": Todo["completed"];
    }
}
declare global {
    interface HTMLTodoAppElement extends Components.TodoApp, HTMLStencilElement {
    }
    var HTMLTodoAppElement: {
        prototype: HTMLTodoAppElement;
        new (): HTMLTodoAppElement;
    };
    interface HTMLTodoFooterElement extends Components.TodoFooter, HTMLStencilElement {
    }
    var HTMLTodoFooterElement: {
        prototype: HTMLTodoFooterElement;
        new (): HTMLTodoFooterElement;
    };
    interface HTMLTodoItemElement extends Components.TodoItem, HTMLStencilElement {
    }
    var HTMLTodoItemElement: {
        prototype: HTMLTodoItemElement;
        new (): HTMLTodoItemElement;
    };
    interface HTMLElementTagNameMap {
        "todo-app": HTMLTodoAppElement;
        "todo-footer": HTMLTodoFooterElement;
        "todo-item": HTMLTodoItemElement;
    }
}
declare namespace LocalJSX {
    interface TodoApp {
    }
    interface TodoFooter {
        "count"?: number;
        "filter"?: Filter;
        "todos"?: Todo[];
    }
    interface TodoItem {
        "_id"?: Todo["id"];
        "_title"?: Todo["title"];
        "completed"?: Todo["completed"];
    }
    interface IntrinsicElements {
        "todo-app": TodoApp;
        "todo-footer": TodoFooter;
        "todo-item": TodoItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "todo-app": LocalJSX.TodoApp & JSXBase.HTMLAttributes<HTMLTodoAppElement>;
            "todo-footer": LocalJSX.TodoFooter & JSXBase.HTMLAttributes<HTMLTodoFooterElement>;
            "todo-item": LocalJSX.TodoItem & JSXBase.HTMLAttributes<HTMLTodoItemElement>;
        }
    }
}
